augment: true
augment_times: 1
augment_times_query: 1
backbone:
  kwargs: null
  name: resnet12
batch_size: 128
classifier:
  kwargs: null
  name: ProtoNet
data_root: /experiments/few_shot_dataset/miniImageNet--ravi
deterministic: true
device_ids: 1
episode_size: 1
epoch: 100
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/Proto.yaml
- backbones/resnet12.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 0.5
    step_size: 20
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.001
  name: Adam
parallel_part:
- emb_func
port: 40532
pretrain_path: null
query_num: 15
rank: 0
result_root: /experiments/few_shot_eval/ProtoNet
resume: false
save_interval: 10
save_part:
- emb_func
seed: 2147483647
shot_num: 1
tag: null
tb_scale: 3.3333333333333335
test_episode: 600
test_epoch: 5
test_query: 15
test_shot: 1
test_way: 5
train_episode: 1000
use_memory: false
warmup: 0
way_num: 5
workers: 8


spurious: true
spurious_mode: online
task_path: null
worst_group: false # for training

tag: spurious-att_vit-gpt2
attribute_path_train: /experiments/few_shot_dataset/miniImageNet--ravi/train_vit-gpt2_attribute_embeds.pickle
attribute_path_val: /experiments/few_shot_dataset/miniImageNet--ravi/val_vit-gpt2_attribute_embeds.pickle
attribute_path_test: /experiments/few_shot_dataset/miniImageNet--ravi/test_vit-gpt2_attribute_embeds.pickle

# tag: spurious-att_blip
# attribute_path_train: /experiments/few_shot_dataset/miniImageNet--ravi/train_blip_attribute_embeds.pickle
# attribute_path_val: /experiments/few_shot_dataset/miniImageNet--ravi/val_blip_attribute_embeds.pickle
# attribute_path_test: /experiments/few_shot_dataset/miniImageNet--ravi/test_blip_attribute_embeds.pickle
