includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/Proto.yaml
  - backbones/resnet12.yaml


device_ids: 0,1
n_gpu: 1
way_num: 5
shot_num: 1
query_num: 15
episode_size: 2
train_episode: 100
test_episode: 100

augment_times: 5
augment_times_query: 5

backbone:
  name: resnet12
  kwargs:
    keep_prob: 0.0

